### ISSUE TITLE
Admin panel/account

### ISSUE THREAD

**Issue by Casvt** [Casvt/MIND#1]
**Is your feature request related to a problem? Please describe.**

Currently there is no way to manage users, recover access to users accounts or change hosting settings from the web-ui. You can change hosting settings by directly editing the `Noted.py` file, but it's not ideal. And there's no way to manage the users.

**Describe the solution you'd like**

A admin user account that you can log into that gives you access to an admin panel where you can manage these settings.

**Additional context**

Reserve the username `admin` for the admin account and force the change password after first login

**Comment by Lord0fBytes** [comment]
Not sure if this is included in this issue, but the locale settings dont persist. Every time I login I have to re-adjust the locale settings. 
If this is not part of this I can create a new issue.

**Comment by Casvt** [comment]
@Lord0fBytes Locale settings are per-client. They should stick between _sessions on the same client_, but not between _different clients_. If you're experiencing behaviour that doesn't match that, please make a new issue. It doesn't have to do with the admin panel.

**Comment by joestump** [comment]
Would love to have some support for Authentik - maybe with a trusted proxy and username header along with the proxy provider in Authentik?
